server:
  port: 8080
 
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
